/**
 * The fixed list an Internal Accreditor picks specializations from, verbatim from
 * `docs/OtherContext.txt` "AREA OF EXPERTISE".
 *
 * BACKEND.md §2.1 estimated ~90 of these. The authoritative list holds 82.
 * Recorded rather than rounded — `accreditor_expertise` needs foreign keys, so the
 * count has to be the real one.
 */
export const EXPERTISE_AREAS: string[] = [
  "Accountancy",
  "Accounting and Finance",
  "Administration and Governance",
  "Anthropology",
  "Applied Mathematics",
  "Architecture",
  "Biology",
  "Broadcasting",
  "Business Administration",
  "Chemistry",
  "Civil Engineering",
  "Communication Research",
  "Computer Engineering",
  "Computer Science",
  "Criminology",
  "Creative Arts",
  "Cultural Studies",
  "Curriculum and Instruction",
  "Curriculum Development",
  "Cybersecurity",
  "Data Science",
  "Development Communication",
  "Economics",
  "Early Childhood Education",
  "Educational Management",
  "Electrical Engineering",
  "Electronics Engineering",
  "English Language Studies",
  "Entrepreneurship",
  "Environmental Science",
  "Event Management",
  "Extension and Community Development",
  "Faculty Development",
  "Filipinolohiya",
  "Fitness and Sports Coaching",
  "History",
  "Hospitality Management",
  "Higher Education Management",
  "Hotel and Restaurant Management",
  "Human Resource Management",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "Journalism",
  "Laboratories Management",
  "Legal Studies",
  "Library and Information Science",
  "Library Services",
  "Manufacturing Engineering",
  "Marketing Management",
  "Mathematics",
  "Mechanical Engineering",
  "Media and Information Studies",
  "Mission, Goals, and Objectives",
  "Music",
  "Network Security",
  "Office Administration",
  "Outcomes-Based Education (OBE)",
  "Performing Arts",
  "Philosophy",
  "Physical Education",
  "Physical Facilities Management",
  "Physics",
  "Political Economy",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Public Governance",
  "Quality Assurance in Higher Education",
  "Railway Engineering",
  "Records Management",
  "Research",
  "Research and Innovation",
  "Secondary Education",
  "Software Engineering",
  "Sociology",
  "Sports Science",
  "Statistics",
  "Student Services and Development",
  "Teacher Education",
  "Theater Arts",
  "Tourism Management",
];
