/**
 * Every degree programme PUP offers, per campus — transcribed from
 * `docs/OtherContext.txt` "PROGRAMS IN EACH CAMPUSES", which is the authority.
 * Nothing here is invented: this file was generated from that section and is now
 * the human-editable source.
 *
 * `college` is set only for the main campus. Off-main-campus programmes have no
 * college, which the `campuses/[campus]` vs `main-campus/[college]` route split
 * in the built portal already assumes.
 *
 * **How the main campus mapping was recovered.** OtherContext.txt lists Sta. Mesa's
 * 97 programmes in exactly the order of the 14-college list, so the boundaries are
 * run lengths: CADBE 3, CAF 3, CAL 5, CBA 7, CCIS 2, COC 4, COED 19, CE 7, CHK 2,
 * CPSPA 5, CS 8, CSSD 7, CTHTM 3, GS 22. Note graduate degrees are *not* all under
 * Graduate School — MBA/DBA sit under CBA, MPA/DPA under CPSPA, the MA Education
 * degrees under COED. See open item O-1; the boundaries still want an owner eyeball,
 * and two are noted in BACKEND-PROGRESS.md as worth a second look.
 *
 * Two lines are duplicated in the source (BTLEd major in ICT, BA in Sociology) and
 * are deduplicated here — open item O-8.
 */
export type ProgramSeed = {
  /** Campus slug — joins `campuses.slug`. */
  campus: string;
  /** College code — joins `colleges.code`. Null for every non-main campus. */
  college: string | null;
  name: string;
};

export const PROGRAMS: ProgramSeed[] = [
  { campus: "alfonso", college: null, name: "Bachelor of Science in Mechanical Engineering" },
  { campus: "alfonso", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "alfonso", college: null, name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "bansud", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "bansud", college: null, name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "bansud", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "bansud", college: null, name: "Bachelor of Public Administration" },
  { campus: "bataan", college: null, name: "Bachelor of Elementary Education" },
  { campus: "bataan", college: null, name: "Bachelor of Science in Accountancy" },
  { campus: "bataan", college: null, name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "bataan", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "bataan", college: null, name: "Bachelor of Science in Industrial Engineering" },
  { campus: "bataan", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "bataan", college: null, name: "Bachelor of Science in Management Accounting" },
  { campus: "binan", college: null, name: "Bachelor of Science in Computer Engineering" },
  { campus: "binan", college: null, name: "Bachelor of Science in Industrial Engineering" },
  { campus: "binan", college: null, name: "Bachelor of Science in Psychology" },
  { campus: "binan", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "binan", college: null, name: "Bachelor of Secondary Education major in Social Studies" },
  { campus: "binan", college: null, name: "Bachelor of Elementary Education" },
  { campus: "binan", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "binan", college: null, name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "cabiao", college: null, name: "Bachelor of Elementary Education" },
  { campus: "cabiao", college: null, name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "calauan", college: null, name: "Bachelor of Technology and Livelihood Education major in Home Economics" },
  { campus: "calauan", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "calauan", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "general-luna", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "general-luna", college: null, name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "general-luna", college: null, name: "Bachelor of Public Administration" },
  { campus: "lopez", college: null, name: "Bachelor of Elementary Education" },
  { campus: "lopez", college: null, name: "Bachelor of Public Administration" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Architecture" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Accountancy" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Agribusiness Management" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Business Administration major in Financial Management" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Biology" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Civil Engineering" },
  { campus: "lopez", college: null, name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Electrical Engineering" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Hospitality Management" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Nutrition and Dietetics" },
  { campus: "lopez", college: null, name: "Bachelor of Science in Office Administration" },
  { campus: "maragondon", college: null, name: "Bachelor of Science in Business Administration major in Financial Management" },
  { campus: "maragondon", college: null, name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "maragondon", college: null, name: "Bachelor of Science in Electrical Engineering" },
  { campus: "maragondon", college: null, name: "Bachelor of Science in Electronics Engineering" },
  { campus: "maragondon", college: null, name: "Bachelor of Science in Mechanical Engineering" },
  { campus: "maragondon", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "mulanay", college: null, name: "Bachelor of Elementary Education" },
  { campus: "mulanay", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "mulanay", college: null, name: "Bachelor of Science in Office Administration" },
  { campus: "mulanay", college: null, name: "Bachelor of Science in Agribusiness Management" },
  { campus: "mulanay", college: null, name: "Bachelor of Public Administration with specialization in Fiscal Administration" },
  { campus: "paranaque", college: null, name: "Bachelor of Science in Office Administration" },
  { campus: "paranaque", college: null, name: "Bachelor of Science in Computer Engineering" },
  { campus: "paranaque", college: null, name: "Bachelor of Science in Hospitality Management" },
  { campus: "paranaque", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "pulilan", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "pulilan", college: null, name: "Bachelor of Public Administration with specialization in Fiscal Administration" },
  { campus: "quezon-city", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "quezon-city", college: null, name: "Bachelor of Technology and Livelihood Education major in Home Economics" },
  { campus: "quezon-city", college: null, name: "Bachelor of Technology and Livelihood Education major in Information and Communication Technology" },
  { campus: "quezon-city", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "quezon-city", college: null, name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "quezon-city", college: null, name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "quezon-city", college: null, name: "Bachelor of Public Administration with specialization in Fiscal Administration" },
  { campus: "quezon-city", college: null, name: "Bachelor of Science in Psychology" },
  { campus: "ragay", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "ragay", college: null, name: "Bachelor of Elementary Education" },
  { campus: "ragay", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "ragay", college: null, name: "Bachelor of Science in Office Administration" },
  { campus: "ragay", college: null, name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "ragay", college: null, name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "sablayan", college: null, name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "sablayan", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "sablayan", college: null, name: "Bachelor of Science in Cooperative Management major in Cooperative Education and Community Development" },
  { campus: "sablayan", college: null, name: "Bachelor of Science in Cooperative Management major in Social Enterprise Management" },
  { campus: "san-juan", college: null, name: "Bachelor of Science in Accountancy" },
  { campus: "san-juan", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "san-juan", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "san-juan", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "san-juan", college: null, name: "Bachelor of Science in Business Administration major in Financial Management" },
  { campus: "san-juan", college: null, name: "Bachelor of Science in Hospitality Management" },
  { campus: "san-juan", college: null, name: "Bachelor of Science in Psychology" },
  { campus: "san-pedro", college: null, name: "Bachelor of Science in Accountancy" },
  { campus: "san-pedro", college: null, name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "san-pedro", college: null, name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "san-pedro", college: null, name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "san-pedro", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "san-pedro", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "san-pedro", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "sta-maria", college: null, name: "Bachelor of Science in Accountancy" },
  { campus: "sta-maria", college: null, name: "Bachelor of Science in Computer Engineering" },
  { campus: "sta-maria", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "sta-maria", college: null, name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "sta-maria", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "sta-maria", college: null, name: "Bachelor of Science in Hospitality Management" },
  { campus: "sta-maria", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "sta-mesa-manila", college: "CADBE", name: "Bachelor of Science in Architecture" },
  { campus: "sta-mesa-manila", college: "CADBE", name: "Bachelor of Science in Interior Design" },
  { campus: "sta-mesa-manila", college: "CADBE", name: "Bachelor of Science in Environmental Planning" },
  { campus: "sta-mesa-manila", college: "CAF", name: "Bachelor of Science in Accountancy" },
  { campus: "sta-mesa-manila", college: "CAF", name: "Bachelor of Science in Business Administration major in Financial Management" },
  { campus: "sta-mesa-manila", college: "CAF", name: "Bachelor of Science in Management Accounting" },
  { campus: "sta-mesa-manila", college: "CAL", name: "Bachelor of Arts in Filipinology" },
  { campus: "sta-mesa-manila", college: "CAL", name: "Bachelor of Arts in Philosophy" },
  { campus: "sta-mesa-manila", college: "CAL", name: "Bachelor of Arts in Literary and Cultural Studies" },
  { campus: "sta-mesa-manila", college: "CAL", name: "Bachelor of Arts in English Language Studies" },
  { campus: "sta-mesa-manila", college: "CAL", name: "Bachelor of Performing Arts" },
  { campus: "sta-mesa-manila", college: "CBA", name: "Bachelor of Science in Entrepreneurship" },
  { campus: "sta-mesa-manila", college: "CBA", name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "sta-mesa-manila", college: "CBA", name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "sta-mesa-manila", college: "CBA", name: "Bachelor of Science in Office Administration" },
  { campus: "sta-mesa-manila", college: "CBA", name: "Bachelor of Science in Real Estate Management" },
  { campus: "sta-mesa-manila", college: "CBA", name: "Master in Business Administration" },
  { campus: "sta-mesa-manila", college: "CBA", name: "Doctor in Business Administration" },
  { campus: "sta-mesa-manila", college: "CCIS", name: "Bachelor of Science in Computer Science" },
  { campus: "sta-mesa-manila", college: "CCIS", name: "Bachelor of Science in Information Technology" },
  { campus: "sta-mesa-manila", college: "COC", name: "Bachelor in Advertising and Public Relations" },
  { campus: "sta-mesa-manila", college: "COC", name: "Bachelor of Arts in Broadcasting" },
  { campus: "sta-mesa-manila", college: "COC", name: "Bachelor of Arts in Communication Research" },
  { campus: "sta-mesa-manila", college: "COC", name: "Bachelor of Arts in Journalism" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Early Childhood Education" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Elementary Education" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Library and Information Science" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Secondary Education major in English" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Secondary Education major in Filipino" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Secondary Education major in Social Studies" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Secondary Education major in Science" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Technology and Livelihood Education major in Home Economics" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Technology and Livelihood Education major in Industrial Arts" },
  { campus: "sta-mesa-manila", college: "COED", name: "Bachelor of Technology and Livelihood Education major in Information and Communication Technology" },
  { campus: "sta-mesa-manila", college: "COED", name: "Master in Library and Information Science" },
  { campus: "sta-mesa-manila", college: "COED", name: "Master of Arts in Education major in Mathematics Education" },
  { campus: "sta-mesa-manila", college: "COED", name: "Master of Arts in Education major in Teaching in the Challenged Areas" },
  { campus: "sta-mesa-manila", college: "COED", name: "Master of Arts in Education Management" },
  { campus: "sta-mesa-manila", college: "COED", name: "Master of Arts in English Language Teaching" },
  { campus: "sta-mesa-manila", college: "CHK", name: "Master of Arts in Physical Education and Sports" },
  { campus: "sta-mesa-manila", college: "COED", name: "Doctor of Philosophy in Education" },
  { campus: "sta-mesa-manila", college: "CE", name: "Bachelor of Science in Civil Engineering" },
  { campus: "sta-mesa-manila", college: "CE", name: "Bachelor of Science in Computer Engineering" },
  { campus: "sta-mesa-manila", college: "CE", name: "Bachelor of Science in Electrical Engineering" },
  { campus: "sta-mesa-manila", college: "CE", name: "Bachelor of Science in Electronics Engineering" },
  { campus: "sta-mesa-manila", college: "CE", name: "Bachelor of Science in Industrial Engineering" },
  { campus: "sta-mesa-manila", college: "CE", name: "Bachelor of Science in Mechanical Engineering" },
  { campus: "sta-mesa-manila", college: "CE", name: "Bachelor of Science in Railway Engineering Management" },
  { campus: "sta-mesa-manila", college: "CHK", name: "Bachelor of Physical Education" },
  { campus: "sta-mesa-manila", college: "CHK", name: "Bachelor of Science in Exercise and Sports Science" },
  { campus: "sta-mesa-manila", college: "CPSPA", name: "Bachelor of Arts in Political Economy" },
  { campus: "sta-mesa-manila", college: "CPSPA", name: "Bachelor of Arts in Political Science" },
  { campus: "sta-mesa-manila", college: "CPSPA", name: "Bachelor of Public Administration" },
  { campus: "sta-mesa-manila", college: "CPSPA", name: "Master of Public Administration" },
  { campus: "sta-mesa-manila", college: "CPSPA", name: "Doctor of Public Administration" },
  { campus: "sta-mesa-manila", college: "CS", name: "Bachelor of Science in Applied Mathematics" },
  { campus: "sta-mesa-manila", college: "CS", name: "Bachelor of Science in Biology" },
  { campus: "sta-mesa-manila", college: "CS", name: "Bachelor of Science in Chemistry" },
  { campus: "sta-mesa-manila", college: "CS", name: "Bachelor of Science in Food Technology" },
  { campus: "sta-mesa-manila", college: "CS", name: "Bachelor of Science in Mathematics" },
  { campus: "sta-mesa-manila", college: "CS", name: "Bachelor of Science in Nutrition and Dietetics" },
  { campus: "sta-mesa-manila", college: "CS", name: "Bachelor of Science in Physics" },
  { campus: "sta-mesa-manila", college: "CS", name: "Bachelor of Science in Statistics" },
  { campus: "sta-mesa-manila", college: "CSSD", name: "Bachelor of Arts in History" },
  { campus: "sta-mesa-manila", college: "CSSD", name: "Bachelor of Arts in Philippine Studies" },
  { campus: "sta-mesa-manila", college: "CSSD", name: "Bachelor of Arts in Sociology" },
  { campus: "sta-mesa-manila", college: "CSSD", name: "Bachelor of Science in Cooperative Management major in Cooperative Education and Community Development" },
  { campus: "sta-mesa-manila", college: "CSSD", name: "Bachelor of Science in Economics" },
  { campus: "sta-mesa-manila", college: "CSSD", name: "Bachelor of Science in Psychology" },
  { campus: "sta-mesa-manila", college: "CTHTM", name: "Bachelor of Science in Hospitality Management" },
  { campus: "sta-mesa-manila", college: "CTHTM", name: "Bachelor of Science in Tourism Management" },
  { campus: "sta-mesa-manila", college: "CTHTM", name: "Bachelor of Science in Transportation Management" },
  { campus: "sta-mesa-manila", college: "GS", name: "Doctor of Philosophy in Communication" },
  { campus: "sta-mesa-manila", college: "GS", name: "Doctor of Philosophy in Economics" },
  { campus: "sta-mesa-manila", college: "GS", name: "Doctor of Philosophy in English Language Studies" },
  { campus: "sta-mesa-manila", college: "GS", name: "Doctor of Philosophy in Filipino" },
  { campus: "sta-mesa-manila", college: "GS", name: "Doctor of Philosophy in Psychology" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master in Applied Statistics" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Arts in Communication" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Arts in English Language Studies" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Arts in Filipino" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Arts in Philippine Studies" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Arts in Psychology" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Arts in Sociology" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in Biology" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in Civil Engineering" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in Computer Engineering" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in Economics" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in Electronics Engineering" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in Industrial Engineering" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in Information Technology" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in International Tourism and Hospitality Management" },
  { campus: "sta-mesa-manila", college: "GS", name: "Master of Science in Nutrition and Dietetics" },
  { campus: "sta-mesa-manila", college: "GS", name: "Professional Science Master's in Railway Engineering Management" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Science in Accountancy" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Science in Management Accounting" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Technology and Livelihood Education major in Home Economics" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Secondary Education major in Filipino" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Science in Electronics Engineering" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Science in Industrial Engineering" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "sta-rosa", college: null, name: "Bachelor of Science in Psychology" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Public Administration with specialization in Fiscal Administration" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Science in Electrical Engineering" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Science in Electronics Engineering" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Science in Industrial Engineering" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Science in Psychology" },
  { campus: "sto-tomas", college: null, name: "Bachelor of Technology and Livelihood Education major in Information and Communication Technology" },
  { campus: "taguig", college: null, name: "Bachelor of Science in Mechanical Engineering" },
  { campus: "taguig", college: null, name: "Bachelor of Science in Electronics Engineering" },
  { campus: "taguig", college: null, name: "Bachelor of Secondary Education major in English" },
  { campus: "taguig", college: null, name: "Bachelor of Secondary Education major in Mathematics" },
  { campus: "taguig", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "taguig", college: null, name: "Bachelor of Science in Business Administration major in Marketing Management" },
  { campus: "taguig", college: null, name: "Bachelor of Science in Business Administration major in Human Resource Management" },
  { campus: "taguig", college: null, name: "Bachelor of Science in Office Administration" },
  { campus: "taguig", college: null, name: "Bachelor of Science in Psychology" },
  { campus: "unisan", college: null, name: "Bachelor of Elementary Education" },
  { campus: "unisan", college: null, name: "Bachelor of Science in Information Technology" },
  { campus: "unisan", college: null, name: "Bachelor of Science in Entrepreneurship" },
  { campus: "unisan", college: null, name: "Bachelor of Public Administration" },
];
