import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";
import type { ReportData } from "@/lib/report-model";

const W = 842;
const H = 595;
const M = 40;
const MAROON = rgb(0.5, 0, 0);
const BAD = rgb(0.78, 0.16, 0.16);
const WARN = rgb(0.7, 0.45, 0);

const clean = (v: string | number) => String(v).replace(/[^\x20-\x7E\xA0-\xFF–—‘’“”•…]/g, "?");

function wrap(text: string, font: PDFFont, size: number, max: number) {
  const lines: string[] = [];
  let cur = "";
  for (const word of text.split(/\s+/)) {
    const next = cur ? `${cur} ${word}` : word;
    if (font.widthOfTextAtSize(next, size) <= max) {
      cur = next;
      continue;
    }
    if (cur) lines.push(cur);
    cur = word;
    while (font.widthOfTextAtSize(cur, size) > max && cur.length > 1) {
      let i = cur.length - 1;
      while (i > 1 && font.widthOfTextAtSize(cur.slice(0, i), size) > max) i--;
      lines.push(cur.slice(0, i));
      cur = cur.slice(i);
    }
  }
  lines.push(cur);
  return lines;
}

export async function reportPdf(r: { title: string; scope: string; asOf: string; by: string }, d: ReportData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const reg = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const seal = await fetch("/assets/portal/mockup/seal.png")
    .then((x) => (x.ok ? x.arrayBuffer() : null))
    .then((b) => (b ? doc.embedPng(b) : null))
    .catch(() => null);

  const size = 8.5;
  const pad = 4;
  const lead = 11;
  const usable = W - M * 2;
  const natural = d.h.map((h, i) => Math.max(bold.widthOfTextAtSize(clean(h), size), ...d.rows.map((row) => Math.min(reg.widthOfTextAtSize(clean(row[i] ?? ""), size), usable * 0.4))) + pad * 2);
  const total = natural.reduce((a, b) => a + b, 0);
  const cw = natural.map((n) => (n / total) * usable);

  let page = doc.addPage([W, H]);
  let y = H - M;
  const header = () => {
    if (seal) page.drawImage(seal, { x: M, y: y - 34, width: 34, height: 34 });
    const tx = seal ? M + 44 : M;
    page.drawText("REPUBLIC OF THE PHILIPPINES", { x: tx, y: y - 8, size: 7, font: reg, color: rgb(0.4, 0.4, 0.4) });
    page.drawText("Polytechnic University of the Philippines", { x: tx, y: y - 19, size: 11, font: bold });
    page.drawText("QUALITY ASSURANCE CENTER", { x: tx, y: y - 31, size: 9, font: bold, color: MAROON });
    y -= 52;
    page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 1.5, color: MAROON });
    y -= 20;
  };
  header();

  const center = (text: string, size: number, font: PDFFont, color = rgb(0, 0, 0)) => {
    const t = clean(text);
    page.drawText(t, { x: (W - font.widthOfTextAtSize(t, size)) / 2, y, size, font, color });
    y -= size + 6;
  };
  center(r.title.toUpperCase(), 14, bold);
  center(`${r.scope} · as of ${r.asOf}`, 9.5, reg, rgb(0.4, 0.4, 0.4));
  y -= 4;
  page.drawRectangle({ x: M, y: y - 18, width: usable, height: 22, color: rgb(0.97, 0.95, 0.95) });
  page.drawText(clean(d.sum), { x: M + 8, y: y - 11, size: 9.5, font: bold });
  y -= 36;

  const headRow = () => {
    page.drawRectangle({ x: M, y: y - lead - pad, width: usable, height: lead + pad * 2, color: MAROON });
    let x = M;
    d.h.forEach((h, i) => {
      page.drawText(clean(h), { x: x + pad, y: y - lead + 2, size, font: bold, color: rgb(1, 1, 1) });
      x += cw[i];
    });
    y -= lead + pad * 2;
  };
  headRow();

  if (!d.rows.length) page.drawText("No programs match these filters.", { x: M + pad, y: y - lead, size, font: reg });

  d.rows.forEach((row, ri) => {
    const cells = row.map((v, i) => wrap(clean(v), reg, size, cw[i] - pad * 2));
    const height = Math.max(...cells.map((c) => c.length)) * lead + pad * 2;
    if (y - height < M + 20) {
      page = doc.addPage([W, H]);
      y = H - M;
      headRow();
    }
    if (ri % 2) page.drawRectangle({ x: M, y: y - height, width: usable, height, color: rgb(0.98, 0.98, 0.98) });
    let x = M;
    cells.forEach((lines, i) => {
      const v = String(row[i]);
      const color = v === "Expired" ? BAD : v === "Expiring" ? WARN : rgb(0, 0, 0);
      lines.forEach((ln, li) => page.drawText(ln, { x: x + pad, y: y - pad - lead * (li + 1) + 3, size, font: v === "Expired" || v === "Expiring" ? bold : reg, color }));
      x += cw[i];
    });
    page.drawLine({ start: { x: M, y: y - height }, end: { x: W - M, y: y - height }, thickness: 0.4, color: rgb(0.88, 0.88, 0.88) });
    y -= height;
  });

  const pages = doc.getPages();
  pages.forEach((p, i) => {
    p.drawText(clean(`Generated by ${r.by} · QAC-WARDS · Form Code: QAC-TPL-01`), { x: M, y: 22, size: 7.5, font: reg, color: rgb(0.45, 0.45, 0.45) });
    const t = `Page ${i + 1} of ${pages.length}`;
    p.drawText(t, { x: W - M - reg.widthOfTextAtSize(t, 7.5), y: 22, size: 7.5, font: reg, color: rgb(0.45, 0.45, 0.45) });
  });
  return doc.save();
}

export async function downloadReportPdf(r: { title: string; scope: string; asOf: string; by: string }, d: ReportData, say: (msg: string, err?: boolean) => void) {
  let bytes: Uint8Array;
  try {
    bytes = await reportPdf(r, d);
  } catch {
    return say("Could not create the PDF", true);
  }
  const url = URL.createObjectURL(new Blob([bytes as BlobPart], { type: "application/pdf" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = `${r.title.replace(/[^\w]+/g, "-")}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  say("PDF downloaded");
}
