-- B8 — Notifications, email outbox, activity logs.
--
-- Two rules from the plan shape this whole file:
--
--   §8.5  Notifications are generated by Postgres triggers, not application
--         code. Every path that can raise one is a database write anyway, and a
--         trigger cannot be forgotten by a future route handler.
--   §2.5  `activity_logs` is written by triggers for the same reason — coverage
--         stops depending on anyone remembering to log.
--
-- Neither table has an INSERT policy. Both are written only by the SECURITY
-- DEFINER functions below, so a client cannot forge a notification for someone
-- else or fabricate an audit entry.

-- ------------------------------------------------------------ notifications

create type public.notification_kind as enum (
  'assignment_issued',
  'assignment_response',
  'submission_received',
  'document_disapproved',
  'score_released',
  'event_scheduled',
  'award_expiring',
  'account'
);

create table public.notifications (
  id           uuid primary key default uuid_generate_v4(),
  recipient_id uuid not null references public.profiles (id) on delete cascade,

  -- Who caused it, when there is a someone. The bell draws an avatar next to
  -- every row; without this it would have nothing to draw for a human action.
  actor_id     uuid references public.profiles (id) on delete set null,

  kind         public.notification_kind not null,
  title        text not null,
  body         text,
  link         text,
  read_at      timestamptz,
  created_at   timestamptz not null default now()
);

create index notifications_recipient_idx
  on public.notifications (recipient_id, created_at desc);

-- The bell's unread count is the hottest read in the portal — it runs on every
-- portal page render. A partial index keeps it off the full table.
create index notifications_unread_idx
  on public.notifications (recipient_id)
  where read_at is null;

-- ------------------------------------------------------------- email outbox
--
-- A trigger cannot open an SMTP connection, so the notification triggers enqueue
-- here and a drain job sends. That split is also what buys decision 14's
-- "retry and a failure log": the attempt count and the last error live on the
-- row, so a failed send is visible rather than lost in a server log.

create type public.email_status as enum ('pending', 'sent', 'failed');

create table public.email_outbox (
  id              uuid primary key default uuid_generate_v4(),
  notification_id uuid references public.notifications (id) on delete set null,
  to_email        text not null,
  subject         text not null,
  body            text not null,
  status          public.email_status not null default 'pending',
  attempts        int not null default 0,
  last_error      text,
  next_attempt_at timestamptz not null default now(),
  sent_at         timestamptz,
  created_at      timestamptz not null default now()
);

-- The drain's claim query: pending rows whose backoff has elapsed, oldest first.
create index email_outbox_pending_idx
  on public.email_outbox (next_attempt_at)
  where status = 'pending';

comment on table public.email_outbox is
  'Decision 14''s four email classes are enqueued here by the notification '
  'triggers and sent by the drain route. Rows are never deleted on success — '
  'the sent history is the delivery log.';

-- ------------------------------------------------------------ activity logs

create table public.activity_logs (
  id           uuid primary key default uuid_generate_v4(),
  actor_id     uuid references public.profiles (id) on delete set null,

  -- 'insert' | 'update' | 'delete', taken from TG_OP rather than named by the
  -- caller, so it cannot describe something other than what happened.
  action_type  text not null,
  target_table text not null,
  target_id    uuid,
  old_value    jsonb,
  new_value    jsonb,
  ip_address   inet,
  created_at   timestamptz not null default now()
);

create index activity_logs_actor_idx  on public.activity_logs (actor_id, created_at desc);
create index activity_logs_target_idx on public.activity_logs (target_table, target_id);

-- Unbounded by nature (§8.3): the /portal/activity list is keyset-paginated on
-- this pair, never OFFSET.
create index activity_logs_keyset_idx on public.activity_logs (created_at desc, id desc);

-- ---------------------------------------------------------------- helpers

/**
 * Raise one notification, and optionally queue the email that goes with it.
 *
 * SECURITY DEFINER because the *recipient* is almost never the actor — a
 * representative cannot insert a row addressed to a QAC user, and should not be
 * able to. Everything that calls this is a trigger.
 */
create or replace function public.notify_user(
  p_recipient uuid,
  p_kind      public.notification_kind,
  p_title     text,
  p_body      text default null,
  p_link      text default null,
  p_actor     uuid default null,
  p_email     boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id    uuid;
  v_email text;
begin
  if p_recipient is null then
    return null;
  end if;

  -- Never notify someone about their own action. The bell is for things that
  -- happened *to* you.
  if p_actor is not null and p_actor = p_recipient then
    return null;
  end if;

  insert into public.notifications (recipient_id, actor_id, kind, title, body, link)
  values (p_recipient, p_actor, p_kind, p_title, p_body, p_link)
  returning id into v_id;

  if p_email then
    select webmail into v_email
    from public.profiles
    where id = p_recipient and is_active;

    if v_email is not null then
      insert into public.email_outbox (notification_id, to_email, subject, body)
      values (v_id, v_email, p_title, coalesce(p_body, p_title));
    end if;
  end if;

  return v_id;
end;
$$;

/**
 * The generic audit writer. Attached to every mutating table by the DO block at
 * the bottom of this file, so adding a table to that list is the whole of
 * wiring it up.
 *
 * `target_id` is read out of the row as JSON rather than named per table: the
 * join tables (program_reps, assignment_accreditors, submission_choices,
 * event_audiences, event_programs) have composite keys and no `id` column at
 * all, and they still deserve a log line.
 */
create or replace function public.log_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old  jsonb;
  v_new  jsonb;
  v_row  jsonb;
  v_ip   inet;
begin
  if tg_op = 'INSERT' then
    v_new := to_jsonb(new);
  elsif tg_op = 'UPDATE' then
    v_old := to_jsonb(old);
    v_new := to_jsonb(new);
  else
    v_old := to_jsonb(old);
  end if;

  v_row := coalesce(v_new, v_old);

  -- PostgREST publishes the request headers as a GUC. It is absent when the
  -- write comes from psql, a migration or the seed, so this must not throw.
  begin
    v_ip := nullif(
      split_part(
        current_setting('request.headers', true)::json ->> 'x-forwarded-for',
        ',', 1
      ),
      ''
    )::inet;
  exception when others then
    v_ip := null;
  end;

  insert into public.activity_logs (
    actor_id, action_type, target_table, target_id, old_value, new_value, ip_address
  )
  values (
    auth.uid(),
    lower(tg_op),
    tg_table_name,
    nullif(v_row ->> 'id', '')::uuid,
    v_old,
    v_new,
    v_ip
  );

  return null;  -- AFTER trigger; the return value is ignored.
end;
$$;

-- ------------------------------------------------- notification triggers
--
-- One function per event in §8.5. Each is deliberately narrow: it fires on the
-- single column transition that means the thing happened, not on any update to
-- the table.

-- 1. Assignment issued → the accreditor who was put on the team.
create or replace function public.notify_assignment_issued()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_program text;
  v_level   text;
begin
  select p.name, l.name
    into v_program, v_level
  from public.assignments a
  join public.submissions s on s.id = a.submission_id
  join public.programs p    on p.id = s.program_id
  join public.accreditation_levels l on l.id = s.level_id
  where a.id = new.assignment_id;

  perform public.notify_user(
    new.profile_id,
    'assignment_issued',
    'You have a new accreditation assignment',
    coalesce(v_program, 'A programme') || ' — ' || coalesce(v_level, 'accreditation'),
    '/portal/assignment',
    auth.uid(),
    true   -- decision 14: assignment lifecycle is an email class.
  );

  return null;
end;
$$;

create trigger notify_assignment_issued
  after insert on public.assignment_accreditors
  for each row execute function public.notify_assignment_issued();

-- 2. Accreditor accepted or declined → the QAC user who made the assignment.
create or replace function public.notify_assignment_response()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_assigner uuid;
  v_actor    text;
begin
  if new.response = old.response then
    return null;
  end if;

  select a.assigned_by into v_assigner
  from public.assignments a
  where a.id = new.assignment_id;

  select given_name || ' ' || surname into v_actor
  from public.profiles where id = new.profile_id;

  perform public.notify_user(
    v_assigner,
    'assignment_response',
    coalesce(v_actor, 'An accreditor') || ' ' || new.response::text || ' an assignment',
    nullif(new.rejection_note, ''),
    '/portal/assignment',
    new.profile_id,
    true
  );

  return null;
end;
$$;

create trigger notify_assignment_response
  after update on public.assignment_accreditors
  for each row execute function public.notify_assignment_response();

-- 3. Submission filed → QAC, who have to assign a team to it.
create or replace function public.notify_submission_received()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_program text;
  v_level   text;
  v_staff   record;
begin
  if old.submitted_at is not null or new.submitted_at is null then
    return null;
  end if;

  select p.name, l.name into v_program, v_level
  from public.programs p, public.accreditation_levels l
  where p.id = new.program_id and l.id = new.level_id;

  for v_staff in
    select id from public.profiles
    where role in ('qac_personnel', 'qac_admin') and is_active
  loop
    perform public.notify_user(
      v_staff.id,
      'submission_received',
      'Submission filed: ' || coalesce(v_program, 'a programme'),
      coalesce(v_level, '') || ' · attempt ' || new.attempt,
      '/portal/submission',
      auth.uid(),
      true   -- decision 14: submission lifecycle.
    );
  end loop;

  return null;
end;
$$;

create trigger notify_submission_received
  after update on public.submissions
  for each row execute function public.notify_submission_received();

-- 4. A document was disapproved → the representatives of that programme.
--    This is the one the rep most needs, because it is the one that costs them
--    work: a disapproved area has to be re-uploaded before the visit.
create or replace function public.notify_document_disapproved()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_program_id uuid;
  v_rep        record;
begin
  if new.decision is not distinct from old.decision or new.decision <> 'disapproved' then
    return null;
  end if;

  select s.program_id into v_program_id
  from public.evaluations e
  join public.assignments a  on a.id = e.assignment_id
  join public.submissions s  on s.id = a.submission_id
  where e.id = new.evaluation_id;

  for v_rep in
    select profile_id from public.program_reps where program_id = v_program_id
  loop
    perform public.notify_user(
      v_rep.profile_id,
      'document_disapproved',
      'A submitted document was disapproved',
      new.label || coalesce(' — ' || nullif(new.note, ''), ''),
      '/portal/submission',
      new.decided_by,
      true   -- decision 14: submission lifecycle.
    );
  end loop;

  return null;
end;
$$;

create trigger notify_document_disapproved
  after update on public.evaluation_items
  for each row execute function public.notify_document_disapproved();

-- 5. Score released → the representatives. Release is the act that grants
--    standing (§2.7), so this is the notification that matters most.
create or replace function public.notify_score_released()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_program_id uuid;
  v_program    text;
  v_rep        record;
begin
  if old.released_at is not null or new.released_at is null then
    return null;
  end if;

  select s.program_id, p.name into v_program_id, v_program
  from public.assignments a
  join public.submissions s on s.id = a.submission_id
  join public.programs p    on p.id = s.program_id
  where a.id = new.assignment_id;

  for v_rep in
    select profile_id from public.program_reps where program_id = v_program_id
  loop
    perform public.notify_user(
      v_rep.profile_id,
      'score_released',
      'Your accreditation result has been released',
      coalesce(v_program, 'Your programme') ||
        coalesce(' — ' || new.outcome::text, '') ||
        coalesce(' · score ' || new.score::text, ''),
      '/portal/submission',
      new.released_by,
      true
    );
  end loop;

  return null;
end;
$$;

create trigger notify_score_released
  after update on public.evaluations
  for each row execute function public.notify_score_released();

-- 6. Event scheduled → its audience.
--
-- This one cannot be a plain AFTER INSERT on `events`: the audience rows are
-- written after the event row, in the same transaction, so at plain-trigger time
-- the fan-out would see an empty audience and mail the whole university. A
-- DEFERRABLE constraint trigger fires at COMMIT, by which point the audience is
-- final — including the deliberate "no audience rows means university-wide"
-- case from B7, which is only distinguishable once the transaction is done.
create or replace function public.notify_event_scheduled()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_person record;
  v_when   text;
begin
  if new.cancelled_at is not null then
    return null;
  end if;

  v_when := to_char(new.start_time at time zone 'Asia/Manila', 'DD Mon YYYY, HH12:MI AM');

  for v_person in
    select distinct pr.id
    from public.profiles pr
    where pr.is_active
      and (
        -- university-wide: no audience rows and no programme rows
        (
          not exists (select 1 from public.event_audiences where event_id = new.id)
          and not exists (select 1 from public.event_programs where event_id = new.id)
        )
        or exists (
          select 1 from public.event_audiences ea
          where ea.event_id = new.id and ea.role = pr.role
        )
        or exists (
          select 1
          from public.event_programs ep
          join public.program_reps rp on rp.program_id = ep.program_id
          where ep.event_id = new.id and rp.profile_id = pr.id
        )
      )
  loop
    perform public.notify_user(
      v_person.id,
      'event_scheduled',
      new.title,
      v_when,
      '/portal/events',
      new.created_by,
      true   -- decision 14: event notices.
    );
  end loop;

  return null;
end;
$$;

create constraint trigger notify_event_scheduled
  after insert on public.events
  deferrable initially deferred
  for each row execute function public.notify_event_scheduled();

-- 7. Award expiring. The one case in §8.5 with no triggering write — nothing
--    happens when a date passes — so it is a job, not a trigger.
--
--    Idempotent by construction: the NOT EXISTS check means running it twice in
--    a day sends nothing twice, which matters because it is reachable from both
--    pg_cron and an HTTP cron route.
create or replace function public.notify_expiring_awards(p_days int default 60)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row   record;
  v_rep   record;
  v_count int := 0;
begin
  for v_row in
    select pa.id, pa.program_id, pa.valid_until, p.name as program_name, l.name as level_name
    from public.program_accreditations pa
    join public.programs p             on p.id = pa.program_id
    join public.accreditation_levels l on l.id = pa.level_id
    where pa.status = 'active'
      and pa.valid_until is not null
      and pa.valid_until between current_date and current_date + p_days
  loop
    for v_rep in
      select profile_id from public.program_reps where program_id = v_row.program_id
    loop
      if not exists (
        select 1 from public.notifications n
        where n.recipient_id = v_rep.profile_id
          and n.kind = 'award_expiring'
          and n.link = '/portal/dashboard'
          and n.body like '%' || v_row.valid_until::text || '%'
      ) then
        perform public.notify_user(
          v_rep.profile_id,
          'award_expiring',
          v_row.program_name || ' — ' || v_row.level_name || ' expires soon',
          'Valid until ' || v_row.valid_until::text || '. Revalidation must be filed before then.',
          '/portal/dashboard',
          null,
          true
        );
        v_count := v_count + 1;
      end if;
    end loop;
  end loop;

  return v_count;
end;
$$;

comment on function public.notify_expiring_awards(int) is
  'Scheduled, not triggered: an award expiring is the passage of time, not a '
  'write. Scheduled below with pg_cron where available; the /api/cron/expiring '
  'route calls the same function so the behaviour does not depend on which '
  'scheduler the deployment has.';

-- pg_cron is present on Supabase but not guaranteed in every local image, and a
-- missing scheduler must not fail the migration — the HTTP route is the fallback
-- path and it needs the function above, which exists either way.
do $$
begin
  create extension if not exists pg_cron;
  perform cron.schedule(
    'notify-expiring-awards',
    '0 1 * * *',
    $cron$select public.notify_expiring_awards();$cron$
  );
exception when others then
  raise notice 'pg_cron unavailable (%); use /api/cron/expiring instead', sqlerrm;
end;
$$;

-- --------------------------------------------------------------------- RLS

alter table public.notifications enable row level security;
alter table public.email_outbox  enable row level security;
alter table public.activity_logs enable row level security;

-- Your own bell, and nobody else's. No insert policy: notifications arrive from
-- the SECURITY DEFINER triggers only, so one user cannot address another.
create policy "recipients read their own notifications"
  on public.notifications for select to authenticated
  using (recipient_id = auth.uid());

create policy "recipients mark their own notifications read"
  on public.notifications for update to authenticated
  using (recipient_id = auth.uid())
  with check (recipient_id = auth.uid());

/**
 * The UPDATE policy above can only decide *which rows* a user may write, not
 * which columns. Without this, "mark as read" is also "rewrite the title and
 * link of a notification the system sent me" — which matters because the body
 * is rendered in the bell and the link is followed on click.
 */
create or replace function public.freeze_notification_columns()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.id           := old.id;
  new.recipient_id := old.recipient_id;
  new.actor_id     := old.actor_id;
  new.kind         := old.kind;
  new.title        := old.title;
  new.body         := old.body;
  new.link         := old.link;
  new.created_at   := old.created_at;
  return new;
end;
$$;

create trigger freeze_notification_columns
  before update on public.notifications
  for each row execute function public.freeze_notification_columns();

-- Decision 17: own actions only; QAC Admin sees all. UC-009's "all users" is
-- read as a manuscript error.
create policy "users read their own activity"
  on public.activity_logs for select to authenticated
  using (actor_id = auth.uid());

create policy "qac admin reads all activity"
  on public.activity_logs for select to authenticated
  using (public.auth_role() = 'qac_admin');

/**
 * The outbox holds webmail addresses and message bodies for everyone, so only
 * QAC Admin touches it.
 *
 * The drain job is an admin *session*, not the service role: `src/lib/supabase/
 * server.ts` states that service role is confined to seeds and migrations, and a
 * key that bypasses every policy in the database is too large a thing to
 * introduce for one queue. So the mailer signs in as a dedicated QAC Admin
 * account and runs under these two policies like any other user.
 *
 * There is still no INSERT policy: rows arrive from `notify_user()` only.
 */
create policy "qac admin reads the email outbox"
  on public.email_outbox for select to authenticated
  using (public.auth_role() = 'qac_admin');

create policy "qac admin marks outbox rows sent or failed"
  on public.email_outbox for update to authenticated
  using (public.auth_role() = 'qac_admin')
  with check (public.auth_role() = 'qac_admin');

-- ------------------------------------------- attach the audit trigger
--
-- One list, one loop. A table added here is fully logged; a table left off is
-- visibly left off. `activity_logs`, `notifications` and `email_outbox` are
-- excluded deliberately — logging the log recurses, and the outbox would write
-- an audit row for every retry.

do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles',
    'accreditor_expertise',
    'program_reps',
    'accreditation_cycles',
    'submissions',
    'submission_choices',
    'submission_documents',
    'assignments',
    'assignment_accreditors',
    'extension_requests',
    'evaluations',
    'evaluation_items',
    'program_accreditations',
    'templates',
    'repository_files',
    'common_documents',
    'ndas',
    'events',
    'event_audiences',
    'event_programs'
  ]
  loop
    execute format(
      'create trigger log_activity after insert or update or delete on public.%I
         for each row execute function public.log_activity()',
      t
    );
  end loop;
end;
$$;
